# Generated by Django 2.2.1 on 2019-05-11 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=20)),
                ('InvoiceAmount', models.IntegerField()),
                ('GSTAmount', models.IntegerField()),
                ('TotalAmount', models.IntegerField()),
                ('InvoiceSubmission', models.DateField()),
                ('InvoiceDueDate', models.DateField()),
                ('InvoiceStatus', models.CharField(choices=[('to_be_sent', 'To Be Sent'), ('sent', 'Sent'), ('recieved_approval', 'Recieved Approval'), ('recieved_payment', 'Recieved Payment')], max_length=20)),
                ('ClientName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvoiceEntry.ClientName')),
            ],
        ),
    ]
